services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: houses-web
    networks:
      - detkiprod_detki-prod-network
    restart: unless-stopped

networks:
  detkiprod_detki-prod-network:
    external: true
