server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json
               image/svg+xml image/jpeg image/png;

    # Долгое кеширование для хешированных ассетов (JS, CSS, модели, текстуры)
    location ~* \.(js|css|glb|hdr|jpg|png|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SPA: все маршруты отдают index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
